export default {
    Ok_back_btn: require("../ImageSource/PublicImages/Ok_back_btn.png"),

    //TabBar
    tab_icon_chat_default: require("../ImageSource/TabBar/tab_icon_chat_default.png"),
    tab_icon_chat_pressed: require("../ImageSource/TabBar/tab_icon_chat_pressed.png"),
    tab_icon_game_default: require("../ImageSource/TabBar/tab_icon_game_default.png"),
    tab_icon_game_pressed: require("../ImageSource/TabBar/tab_icon_game_pressed.png"),
    tab_icon_mine_default: require("../ImageSource/TabBar/tab_icon_mine_default.png"),
    tab_icon_mine_pressed: require("../ImageSource/TabBar/tab_icon_mine_pressed.png"),
    tab_icon_okpay_default: require("../ImageSource/TabBar/tab_icon_okpay_default.png"),
    tab_icon_okpay_pressed: require("../ImageSource/TabBar/tab_icon_okpay_pressed.png"),
    tab_icon_store_default: require("../ImageSource/TabBar/tab_icon_store_default.png"),
    tab_icon_store_pressed: require("../ImageSource/TabBar/tab_icon_store_pressed.png"),
    tabOk: require("../ImageSource/TabBar/tabOk.png"),
    tabokN: require("../ImageSource/TabBar/tabokN.png"),

    //Home
    computing_power_icon: require("../ImageSource/Home/computing_power_icon.png"),
    gema_yxrk: require("../ImageSource/Home/gema_yxrk.png"),
    mineral_huoqusuanli_btn: require("../ImageSource/Home/mineral_huoqusuanli_btn.png"),
    Mineral_jewel_btn: require("../ImageSource/Home/Mineral_jewel_btn.png"),
    mineral_jifen_icon: require("../ImageSource/Home/mineral_jifen_icon.png"),
    Mineral_star_img: require("../ImageSource/Home/Mineral_star_img.png"),
    mineral_ufo_img: require("../ImageSource/Home/mineral_ufo_img.png"),
    mineral_wanzhuanokpay_btn: require("../ImageSource/Home/mineral_wanzhuanokpay_btn.png"),
    mineral_yuhangyuan_img: require("../ImageSource/Home/mineral_yuhangyuan_img.png"),
    rank_first_icon: require("../ImageSource/Home/rank_first_icon.png"),
    rank_second_icon: require("../ImageSource/Home/rank_second_icon.png"),
    rank_third_icon: require("../ImageSource/Home/rank_third_icon.png"),
    back_white_btn: require("../ImageSource/Home/back_white_btn.png"),
    my_rank_icon: require("../ImageSource/Home/my_rank_icon.png"),
    wallet_title_bg: require("../ImageSource/Home/wallet_title_bg.jpg"),

    //Shop
    chat_bitmap_img: require("../ImageSource/Shop/chat_bitmap_img.png"),
    disLike: require("../ImageSource/Shop/disLike.png"),
    icon_order: require("../ImageSource/Shop/icon_order.png"),
    icon_ProjectActivities: require("../ImageSource/Shop/icon_ProjectActivities.png"),
    icon_supermarket: require("../ImageSource/Shop/icon_supermarket.png"),
    like_blank: require("../ImageSource/Shop/like_blank.png"),
    love: require("../ImageSource/Shop/love.png"),
    menu: require("../ImageSource/Shop/menu.png"),
    my_bg: require("../ImageSource/Shop/my_bg.jpg"),
    search: require("../ImageSource/Shop/search.png"),
    shopcart: require("../ImageSource/Shop/shopcart.png"),
    icon_promotions: require("../ImageSource/Shop/icon_promotions.png"),

    //Mine
    general_level_bg: require("../ImageSource/Mine/general_level_bg.png"),
    my_invitefriends_icon: require("../ImageSource/Mine/my_invitefriends_icon.png"),
    my_next_btn: require("../ImageSource/Mine/my_next_btn.png"),
    my_settings_icon: require("../ImageSource/Mine/my_settings_icon.png"),
    my_suggestion_icon: require("../ImageSource/Mine/my_suggestion_icon.png"),
    my_top_bg: require("../ImageSource/Mine/my_top_bg.png"),
    open_shop_apply: require("../ImageSource/Mine/open_shop_apply.png"),
    tourist_level_bg: require("../ImageSource/Mine/tourist_level_bg.png"),
    vip_level_bg: require("../ImageSource/Mine/vip_level_bg.png"),
    my_person_icon: require("../ImageSource/Mine/my_person_icon.png"),
    wallet_next_btn: require("../ImageSource/Mine/wallet_next_btn.png"),
}